version: '3.8'
services:
  app:
    image: kiszkahubert/backend-int:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/data
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: docker
    restart: on-failure

  db:
    image: kiszkahubert/baza-int:latest
    environment:
      POSTGRES_DB: data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

